landscapeName: lfenergy
landscapeMemberClasses:
   - name: Strategic Membership
     category: Strategic
   - name: Premier Membership
     category: Strategic
   - name: General Membership
     category: General
   - name: Associate Membership
     category: Associate
project: a094100001Cb6HaAAJ # LF Energy Foundation
landscapeMemberCategory: LF Energy Member
landscapefile: landscape.yml
memberSuffix: ' (member)'
missingcsvfile: missing.csv
