landscapeName: lfenergy
landscapeMemberClasses:
  - name: Strategic Membership
    category: Strategic
  - name: Premier Membership
    category: Strategic
  - name: General Membership
    category: General
  - name: Associate Membership
    category: Associate
project: a094100001Cb6HaAAJ # LF Energy Foundation
slug: lfenergy
landscapeMemberCategory: LF Energy Member
landscapeProjectsCategory: LF Energy Projects
landscapeProjectsSubcategories:
  - name: Graduated
    category: Graduated
  - name: Early Adoption
    category: Early Adoption
  - name: Incubating
    category: Incubating
  - name: Sandbox
    category: Sandbox
  - name: SIG
    category: SIG
landscapeProjectsLevels:
  - level: graduated
    name: Graduated
  - level: earlyadoption
    name: Early Adoption
  - level: incubating
    name: Incubating
  - level: sandbox
    name: Sandbox
  - level: sig
    name: SIG
landscapefile: landscape.yml
projectsDefaultCrunchbase: https://www.crunchbase.com/organization/lf-energy
memberSuffix: ' (member)'
tacAgendaProjectUrl: https://github.com/orgs/lf-energy/projects/2/views/2
artworkRepoUrl: "https://artwork.lfenergy.org/projects/{slug}"
