global:
  name: LF Energy Interactive Landscape
  short_name: LFEnergy
  repo: lf-energy/lfenergy-landscape
  website: https://landscape.lfenergy.org
  short_domain: l.lfenergy.org
  company_url: https://lfenergy.org
  membership: LF Energy Member
  email: info@lfenergy.org
  self: https://www.crunchbase.com/organization/lf-energy
  meta:
    title: LF Energy Landscape
    fb_admin: lmays
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: LFE_Foundation
    google_site_verification: eZAQgcvgZbehffBtw1azh327yJwPL0bCsCGbMmkfdBc
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    companies: LF Energy Member
twitter:
  search: landscape.lfenergy.org
  url: https://landscape.lfenergy.org
  text: LF Energy Landscape from @LFE_Foundation
relation:
  label: LF Energy Relation
  url: lfenergy
  values:
    - id: hosted
      label: LF Energy Projects
      children:
        - id: graduated
          label: Technical Project - Graduated
          prefix: LF Energy Technical Project
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Technical Project - Graduated
          big_picture_color: rgb(24,54,114)
          additional_relation: member
        - id: earlyadoption
          label: Technical Project - Early Adoption
          prefix: LF Energy Technical Project
          tag: Early Adoption
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Technical Project - Early Adoption
          big_picture_color: rgb(24,54,114)
          additional_relation: member
        - id: incubation
          label: Technical Project - Incubation
          prefix: LF Energy Technical Project
          tag: Incubation
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Technical Project - Incubation
          big_picture_color: rgb(24,54,114)
          additional_relation: member
        - id: sandbox
          label: Technical Project - Sandbox
          prefix: LF Energy Technical Project
          tag: Sandbox
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Technical Project - Sandbox
          big_picture_color: rgb(24,54,114)
          additional_relation: member
        - id: emeritus
          label: Technical Project - Emeritus
          prefix: LF Energy Technical Project
          tag: Emeritus
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Technical Project - Emeritus
          big_picture_color: rgb(24,54,114)
          additional_relation: member
        - id: stable
          label: Standards Project - Stable
          prefix: LF Energy Standards Project
          tag: Stable
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Standards Project - Stable
          big_picture_color: rgb(83,113,189)
          additional_relation: member
        - id: development
          label: Standards Project - Development
          prefix: LF Energy Standards Project
          tag: Development
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Standards Project - Development
          big_picture_color: rgb(83,113,189)
          additional_relation: member
        - id: sandboxs
          label: Standards Project - Sandbox
          prefix: LF Energy Standards Project
          tag: Sandbox
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Standards Project - Sandbox
          big_picture_color: rgb(83,113,189)
          additional_relation: member
        - id: emerituss
          label: Standards Project - Emeritus
          prefix: LF Energy Standards Project
          tag: Emeritus
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Standards Project - Emeritus
          big_picture_color: rgb(83,113,189)
          additional_relation: member
        - id: active
          label: Working Group - Active
          prefix: LF Energy Working Group
          tag: Active
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Working Group - Active
          big_picture_color: rgb(108,165,209)
          additional_relation: member
        - id: sandboxw
          label: Working Group - Sandbox
          prefix: LF Energy Working Group
          tag: Sandbox
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Working Group - Sandbox
          big_picture_color: rgb(108,165,209)
          additional_relation: member
        - id: emeritusw
          label: Working Group - Emeritus
          prefix: LF Energy Working Group
          tag: Emeritus
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Working Group - Emeritus
          big_picture_color: rgb(108,165,209)
          additional_relation: member
    - id: company
      label: LF Energy Members
      tag: Company
    - id: member
      label: LF Energy Member Products/Projects
      tag: LF Energy Member
    - id: false
      label: Non-LF Energy Member Products/Projects
      url: 'no'
membership:
  Strategic:
    name: LF Energy
    label: Strategic Member
    funding: Strategic
    is_large: true
  General:
    name: LF Energy
    label: Member
    funding: General
  Associate:
    name: LF Energy
    label: Associate
    funding: Associate
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF Energy Interactive Landscape</h1>  <p>The LF Energy Interactive Landscape is a tool for exploring the open source ecosystem in the energy
    industry.</p> <h2><a
    href="https://github.com/lf-energy/lfenergy-landscape/issues/new?assignees=jmertic%2CYarille&labels=new+entry&template=new-landscape-entry.yml&title=New+Landscape+Entry+-+%5BPROJECT%5D">Click
    here</a> to add a new entry to the landscape<h2> <h2><a
    href="https://github.com/lf-energy/lfenergy-landscape/issues/new?assignees=jmertic%2CYarille&labels=update+entry&template=update-landscape-entry.yml&title=Update+Landscape+Entry+for+%5BPROJECT%5D">Click
    here</a> to update an existing landscape entry</h2>
ads:
  - url: https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/?utm_source=lfenergy_landscape&utm_medium=web&utm_campaign=kccncna19
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /category=lf-energy-member-company&format=card-mode&grouping=category
    label: Member cards
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: LF Energy Landscape
    fullscreen_header: See the interactive landscape at l.lfenergy.org
    elements:
      - type: HorizontalCategory
        category: Customer and Market
        rows: 4
        width: 600
        height: 300
        top: 0
        left: 0
        color: rgb(0,206,209)
        fit_width: true
      - type: HorizontalCategory
        category: System Management
        rows: 4
        width: 600
        height: 300
        top: 0
        left: 610
        color: rgb(106,44,218)
        fit_width: true
      - type: HorizontalCategory
        category: Asset Management
        rows: 4
        width: 600
        height: 300
        top: 540
        left: 610
        color: rgb(179,60,133)
        fit_width: true
      - type: HorizontalCategory
        category: Shared
        rows: 4
        width: 890
        height: 200
        top: 315
        left: 0
        color: rgb(29,119,164)
        fit_width: true
      - type: HorizontalCategory
        category: Acquisition and Control
        rows: 4
        width: 600
        height: 300
        top: 540
        left: 0
        color: rgb(37,81,209)
        fit_width: true
      - type: LandscapeInfo
        width: 300
        height: 200
        top: 315
        left: 910
        children:
          - type: text
            text: >-
              This LF Energy Landscape is a living document that developers, investors, vendors, researchers and others can use as a resource to better
              understand the open energy ecosystem.
            top: 55
            left: 120
            right: 20
            font_size: 10
          - type: image
            image: qr.svg
            top: 55
            left: 10
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.lfenergy.org
            top: 150
            left: 19
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 160
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 25
            top: 15
            title: LF Energy Logo
  third:
    tab_index: 1
    url: members
    name: Members
    title: LF Energy Members
    fullscreen_header: Become an LF Energy at member at www.lfenergy.org/join/
    fullscreen_hide_grey_logos: true
    elements:
      - type: HorizontalCategory
        category: Strategic
        rows: 3
        width: 1210
        height: 200
        top: 0
        left: 0
        color: '#e5e4e2'
        fit_width: true
      - type: HorizontalCategory
        category: General
        rows: 3
        width: 1210
        height: 400
        top: 210
        left: 0
        color: '#C0C0C0'
        fit_width: true
      - type: HorizontalCategory
        category: Associate
        rows: 3
        width: 1210
        height: 200
        top: 620
        left: 0
        color: rgb(0,0,0)
        fit_width: true
    category: LF Energy Member
test:
  header: LF Energy Interactive Landscape
  section: LF Energy Members
  logo: operator-fabric.svg
anonymous_organization:
  name: Non-Public Unnamed Organization
  homepage: https://www.cncf.io
  city: Bouvet Island
  region: Antarctica
  country: Antarctica
  twitter: https://twitter.com/CloudNativeFdn
prerender:
  members: /card-mode?category=lf-energy-member&grouping=category&embed=yes&style=borderless
  hosted_projects: /card-mode?grouping=no&project=graduated,earlyadoption,incubation,sandbox,stable,development,sandboxs,active,sandboxw&style=borderless&embed=yes
  hosted_projects_grouped: card-mode?project=graduated,earlyadoption,incubation,sandbox,stable,development,sandboxs,active,sandboxw&style=borderless&embed=yes
  opensustaintech: /card-mode?category=renewable-energy,energy-storage,energy-systems,consumption-of-energy-and-resources,emissions,industrial-ecology,earth-systems,climate-and-earth-science,natural-resources,sustainable-development&grouping=category
export: {}
