global:
  name: LF Energy Interactive Landscape
  short_name: LFEnergy
  repo: lf-energy/lfenergy-landscape
  website: 'https://landscape.lfenergy.org'
  short_domain: l.lfenergy.org
  company_url: 'https://lfenergy.org'
  membership: LF Energy Member Company
  email: info@lfenergy.org
  meta:
    title: LF Energy Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: 'LFE_Foundation'
    google_site_verification: M_GmEYdzsEnvJiIcvfj7gmczKsme1N5rd9RwRD35Y98
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    cncf_sandbox: false
    companies: LF Energy Member Company
    hide_license_for_categories:
      - .ORG
twitter:
  search: landscape.lfenergy.org
  url: 'https://landscape.lfenergy.org'
  text: LF Energy Landscape from @LFE_Foundation
relation:
  label: LF Energy Relation
  url: lfenergy
  values:
    - id: hosted
      label: LF Energy Projects
      children:
        - id: at_large
          label: Stage 1 At Large
          prefix: LF Energy
          tag: At Large
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Energy At Large
          big_picture_color: 'rgb(24,54,114)'
        - id: growth
          label: Stage 2 Growth
          prefix: LF Energy
          tag: Growth
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Energy Growth
          big_picture_color: 'rgb(24,54,114)'
        - id: impact
          label: Stage 3 Impact
          prefix: LF Energy
          tag: Impact
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Energy Impact
          big_picture_color: 'rgb(24,54,114)'
        - id: emeritus
          label: Stage 4 Emeritus
          prefix: LF Energy
          tag: Emeritus
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Energy Emeritus
          big_picture_color: 'rgb(24,54,114)'
    - id: company
      label: LF Energy Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: LF Energy Member Products/Projects
      tag: LF Energy Member
    - id: false
      label: Non-LF Energy Member Products/Projects
      url: 'no'
membership:
  Premium:
    name: LF Energy
    label: Premier Member
    funding: Premier
  General:
    name: LF Energy
    label: Member
    funding: General
  Associate:
    name: LF Energy
    label: Associate
    funding: Associate
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF Energy Interactive Landscape</h1> The LF Energy landscape (<a target="_blank" href="images/landscape.png">png</a>,  <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the  <a href="http://landscape.cncf.io">CNCF</a> and the <a
    href="http://landscape.lfenergy.org">LF Energy Foundation</a> landscapes and based on the same open source code.
  footer: null
ads:
  - url: 'https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/?utm_source=lfenergy_landscape&utm_medium=web&utm_campaign=kccncna19'
    image: /images/info1.jpg
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: LF Energy Landscape
    fullscreen_header: See the interactive landscape at l.lfenergy.org
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 2050
      height: 600
    fullscreen_size:
      width: 2050
      height: 600
    elements:
      - type: HorizontalCategory
        category: .ORG
        rows: 3
        width: 350
        height: 200
        top: 0
        left: 0
        color: 'rgb(78,171,207)'
        fit_width: true
      - type: HorizontalCategory
        category: Traffic Routing
        rows: 3
        width: 545
        height: 200
        top: 0
        left: 370
        color: 'rgb(104, 145, 145)'
        fit_width: true
      - type: HorizontalCategory
        category: Platforms
        rows: 3
        width: 1060
        height: 200
        top: 0
        left: 940
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: Security
        rows: 3
        width: 250
        height: 160
        top: 220
        left: 410
        color: 'rgb(74, 131, 104)'
        fit_width: true
      - type: HorizontalCategory
        category: Networking
        rows: 3
        width: 340
        height: 160
        top: 220
        left: 670
        color: 'rgb(74, 131, 104)'
        fit_width: true
      - type: HorizontalCategory
        category: Infrastructure
        rows: 3
        width: 350
        height: 160
        top: 220
        left: 1020
        color: 'rgb(74, 131, 104)'
        fit_width: true
      - type: HorizontalCategory
        category: Other Energy Related Software
        rows: 3
        width: 620
        height: 160
        top: 220
        left: 1380
        color: 'rgb(64, 131, 104)'
        fit_width: true
      - type: HorizontalCategory
        category: Hardware
        rows: 3
        width: 260
        height: 160
        top: 400
        left: 0
        color: 'rgb(142, 209, 216)'
        fit_width: true
      - type: HorizontalCategory
        category: Energy OEMs
        rows: 3
        width: 460
        height: 160
        top: 400
        left: 280
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: Wireless & Wireline
        rows: 3
        width: 460
        height: 160
        top: 400
        left: 750
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: Real Estate / Land
        rows: 3
        width: 460
        height: 160
        top: 400
        left: 1220
        color: 'rgb(108, 135, 75)'
        fit_width: true
      - type: HorizontalCategory
        category: Services / System Integrators
        rows: 3
        width: 310
        height: 160
        top: 400
        left: 1690
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: LF Energy Member Company
        rows: 10
        width: 2000
        height: 350
        top: 580
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: LandscapeInfo
        width: 390
        height: 160
        top: 220
        left: 5
        children:
          - type: text
            text: >
              The intent is for the Landscape to be a living document that developers, investors, vendors, researchers and others can use as a resource on the
              landscape of Energy computing.
            top: 20
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 15
            left: 5
            width: 90
            height: 90
          - type: title
            title: l.lfenergy.org
            top: 104
            left: 19
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 20
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 60
test:
  header: LF Energy Interactive Landscape
  section: Stage 2 Growth
  logo: project-eve.svg
update_server:
  ip: 147.75.106.211
  update_hour: 0
  update_minute: 0
