global:
  name: LF Energy Interactive Landscape
  short_name: LFEnergy
  repo: lf-energy/lfenergy-landscape
  website: 'https://landscape.lfenergy.org'
  short_domain: l.lfenergy.org
  company_url: 'https://lfenergy.org'
  membership: LF Energy Member
  email: info@lfenergy.org
  self: 'https://www.crunchbase.com/organization/lf-energy'
  meta:
    title: LF Energy Landscape
    fb_admin: jefro
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: LFE_Foundation
    google_site_verification: eZAQgcvgZbehffBtw1azh327yJwPL0bCsCGbMmkfdBc
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    companies: LF Energy Member
twitter:
  search: landscape.lfenergy.org
  url: 'https://landscape.lfenergy.org'
  text: LF Energy Landscape from @LFE_Foundation
relation:
  label: LF Energy Relation
  url: lfenergy
  values:
    - id: hosted
      label: LF Energy Projects
      children:
        - id: incubation
          label: Incubation
          prefix: LF Energy
          tag: Incubation
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Energy Incubation
          big_picture_color: 'rgb(24,54,114)'
        - id: earlyadoption
          label: Early Adoption
          prefix: LF Energy
          tag: Early Adoption
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Energy Early Adoption
          big_picture_color: 'rgb(24,54,114)'
        - id: graduated
          label: Graduated
          prefix: LF Energy
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Energy Graduated
          big_picture_color: 'rgb(24,54,114)'
          additional_relation: member
    - id: company
      label: LF Energy Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: LF Energy Member Products/Projects
      tag: LF Energy Member
    - id: false
      label: Non-LF Energy Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: LF Energy
    label: Premier Member
    funding: Premier
    is_large: true
  General:
    name: LF Energy
    label: Member
    funding: General
  Associate:
    name: LF Energy
    label: Associate
    funding: Associate
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF Energy Interactive Landscape</h1> The LF Energy landscape (<a target="_blank" href="images/landscape.png">png</a>,  <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the  <a href="http://landscape.cncf.io">CNCF Landscape</a> and
    based on the same open source code.
  footer: null
ads:
  - url: 'https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/?utm_source=lfenergy_landscape&utm_medium=web&utm_campaign=kccncna19'
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /category=lf-energy-member-company&format=card-mode&grouping=category
    label: Member cards
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: LF Energy Landscape
    fullscreen_header: See the interactive landscape at l.lfenergy.org
    elements:
      - type: HorizontalCategory
        category: System Management
        rows: 2
        width: 500
        height: 200
        top: 20
        left: 0
        color: 'rgb(106,44,218)'
        fit_width: true
      - type: HorizontalCategory
        category: Customer and Market
        rows: 2
        width: 500
        height: 200
        top: 20
        left: 520
        color: 'rgb(179,60,133)'
        fit_width: true
      - type: HorizontalCategory
        category: Acquisition and Control
        rows: 2
        width: 500
        height: 200
        top: 240
        left: 0
        color: 'rgb(29,119,164)'
        fit_width: true
      - type: HorizontalCategory
        category: Shared
        rows: 2
        width: 500
        height: 200
        top: 660
        left: 0
        color: 'rgb(193,83,21)'
        fit_width: true
      - type: HorizontalCategory
        category: LF Energy Member
        rows: 3
        width: 900
        height: 170
        top: 900
        left: 
        color: 'rgb(37,81,209)'
        fit_width: true
      - type: LandscapeInfo
        width: 280
        height: 200
        top: 900
        left: 920
        children:
          - type: text
            text: >-
              This LF Energy Landscape is a living document that developers, investors, vendors, researchers and others can use as a resource to better
              understand the open energy ecosystem.
            top: 55
            left: 120
            right: 20
            font_size: 10
          - type: image
            image: qr.svg
            top: 55
            left: 10
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.lfenergy.org
            top: 150
            left: 19
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 160
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 25
            top: 15
            title: LF Energy Logo
test:
  header: LF Energy Interactive Landscape
  section: Early Adoption
  logo: operator-fabric.svg
